version: '3.8'

services:
  # PostgreSQL数据库服务
  postgres:
    image: postgres:15-alpine
    container_name: novelai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: novelai
      TZ: Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - novelai-network

  # NovelAI应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novelai-app
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=novelai
      - TZ=Asia/Shanghai
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8888:8888"
    networks:
      - novelai-network

# 持久化存储卷
volumes:
  postgres_data:
    driver: local

# 自定义网络
networks:
  novelai-network:
    driver: bridge
