// Code generated by hertz generator. DO NOT EDIT.
// This router file is not needed since background should be only private backend only
package background

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	//background "novelai/biz/handler/background"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

}
