// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.3
// source: save.proto

package save

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Save 保存模型
// 表示用户的保存项，包含保存内容、类型、状态等信息
type Save struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" form:"id" json:"id,omitempty" query:"id"`                                                                             // 保存项ID
	UserId          int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" form:"user_id" json:"user_id,omitempty" query:"user_id"`                                             // 用户ID
	SaveId          string `protobuf:"bytes,3,opt,name=save_id,json=saveId,proto3" form:"save_id" json:"save_id,omitempty" query:"save_id"`                                              // 保存项唯一标识符
	SaveName        string `protobuf:"bytes,4,opt,name=save_name,json=saveName,proto3" form:"save_name" json:"save_name,omitempty" query:"save_name"`                                    // 保存项名称
	SaveDescription string `protobuf:"bytes,5,opt,name=save_description,json=saveDescription,proto3" form:"save_description" json:"save_description,omitempty" query:"save_description"` // 保存项描述
	SaveData        string `protobuf:"bytes,6,opt,name=save_data,json=saveData,proto3" form:"save_data" json:"save_data,omitempty" query:"save_data"`                                    // 保存的具体内容（如JSON字符串）
	SaveType        string `protobuf:"bytes,7,opt,name=save_type,json=saveType,proto3" form:"save_type" json:"save_type,omitempty" query:"save_type"`                                    // 保存类型（如草稿、配置等）
	SaveStatus      string `protobuf:"bytes,8,opt,name=save_status,json=saveStatus,proto3" form:"save_status" json:"save_status,omitempty" query:"save_status"`                          // 保存状态（如active、deleted等）
	CreatedAt       int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" form:"created_at" json:"created_at,omitempty" query:"created_at"`                              // 创建时间（unix时间戳）
	UpdatedAt       int64  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" form:"updated_at" json:"updated_at,omitempty" query:"updated_at"`                             // 更新时间（unix时间戳）
}

func (x *Save) Reset() {
	*x = Save{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Save) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Save) ProtoMessage() {}

func (x *Save) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Save.ProtoReflect.Descriptor instead.
func (*Save) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{0}
}

func (x *Save) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Save) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Save) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

func (x *Save) GetSaveName() string {
	if x != nil {
		return x.SaveName
	}
	return ""
}

func (x *Save) GetSaveDescription() string {
	if x != nil {
		return x.SaveDescription
	}
	return ""
}

func (x *Save) GetSaveData() string {
	if x != nil {
		return x.SaveData
	}
	return ""
}

func (x *Save) GetSaveType() string {
	if x != nil {
		return x.SaveType
	}
	return ""
}

func (x *Save) GetSaveStatus() string {
	if x != nil {
		return x.SaveStatus
	}
	return ""
}

func (x *Save) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Save) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建保存请求
type CreateSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" form:"user_id" json:"user_id,omitempty" query:"user_id"`                                             // 用户ID
	Token           string `protobuf:"bytes,2,opt,name=token,proto3" form:"token" json:"token,omitempty" query:"token"`                                                                  // 用户认证令牌
	SaveName        string `protobuf:"bytes,3,opt,name=save_name,json=saveName,proto3" form:"save_name" json:"save_name,omitempty" query:"save_name"`                                    // 保存项名称
	SaveDescription string `protobuf:"bytes,4,opt,name=save_description,json=saveDescription,proto3" form:"save_description" json:"save_description,omitempty" query:"save_description"` // 保存项描述
	SaveData        string `protobuf:"bytes,5,opt,name=save_data,json=saveData,proto3" form:"save_data" json:"save_data,omitempty" query:"save_data"`                                    // 保存的具体内容
	SaveType        string `protobuf:"bytes,6,opt,name=save_type,json=saveType,proto3" form:"save_type" json:"save_type,omitempty" query:"save_type"`                                    // 保存类型
}

func (x *CreateSaveRequest) Reset() {
	*x = CreateSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaveRequest) ProtoMessage() {}

func (x *CreateSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaveRequest.ProtoReflect.Descriptor instead.
func (*CreateSaveRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSaveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSaveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateSaveRequest) GetSaveName() string {
	if x != nil {
		return x.SaveName
	}
	return ""
}

func (x *CreateSaveRequest) GetSaveDescription() string {
	if x != nil {
		return x.SaveDescription
	}
	return ""
}

func (x *CreateSaveRequest) GetSaveData() string {
	if x != nil {
		return x.SaveData
	}
	return ""
}

func (x *CreateSaveRequest) GetSaveType() string {
	if x != nil {
		return x.SaveType
	}
	return ""
}

// 创建保存响应
type CreateSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`                        // 状态码：0-成功，非0-失败
	Message string `protobuf:"bytes,2,opt,name=message,proto3" form:"message" json:"message,omitempty" query:"message"`             // 响应消息
	SaveId  string `protobuf:"bytes,3,opt,name=save_id,json=saveId,proto3" form:"save_id" json:"save_id,omitempty" query:"save_id"` // 保存项ID
}

func (x *CreateSaveResponse) Reset() {
	*x = CreateSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaveResponse) ProtoMessage() {}

func (x *CreateSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaveResponse.ProtoReflect.Descriptor instead.
func (*CreateSaveResponse) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSaveResponse) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

// 获取保存请求
type GetSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" form:"user_id" json:"user_id,omitempty" query:"user_id"` // 用户ID
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" form:"token" json:"token,omitempty" query:"token"`                      // 用户认证令牌
	SaveId string `protobuf:"bytes,3,opt,name=save_id,json=saveId,proto3" form:"save_id" json:"save_id,omitempty" query:"save_id"`  // 保存项ID
}

func (x *GetSaveRequest) Reset() {
	*x = GetSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaveRequest) ProtoMessage() {}

func (x *GetSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaveRequest.ProtoReflect.Descriptor instead.
func (*GetSaveRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSaveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSaveRequest) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

// 获取保存响应
type GetSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`            // 状态码：0-成功，非0-失败
	Message string `protobuf:"bytes,2,opt,name=message,proto3" form:"message" json:"message,omitempty" query:"message"` // 响应消息
	Save    *Save  `protobuf:"bytes,3,opt,name=save,proto3" form:"save" json:"save,omitempty" query:"save"`             // 保存项信息
}

func (x *GetSaveResponse) Reset() {
	*x = GetSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaveResponse) ProtoMessage() {}

func (x *GetSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaveResponse.ProtoReflect.Descriptor instead.
func (*GetSaveResponse) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{4}
}

func (x *GetSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSaveResponse) GetSave() *Save {
	if x != nil {
		return x.Save
	}
	return nil
}

// 更新保存请求
type UpdateSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" form:"user_id" json:"user_id,omitempty" query:"user_id"`                                             // 用户ID
	Token           string `protobuf:"bytes,2,opt,name=token,proto3" form:"token" json:"token,omitempty" query:"token"`                                                                  // 用户认证令牌
	SaveId          string `protobuf:"bytes,3,opt,name=save_id,json=saveId,proto3" form:"save_id" json:"save_id,omitempty" query:"save_id"`                                              // 保存项ID
	SaveName        string `protobuf:"bytes,4,opt,name=save_name,json=saveName,proto3" form:"save_name" json:"save_name,omitempty" query:"save_name"`                                    // 保存项名称
	SaveDescription string `protobuf:"bytes,5,opt,name=save_description,json=saveDescription,proto3" form:"save_description" json:"save_description,omitempty" query:"save_description"` // 保存项描述
	SaveData        string `protobuf:"bytes,6,opt,name=save_data,json=saveData,proto3" form:"save_data" json:"save_data,omitempty" query:"save_data"`                                    // 保存的具体内容
	SaveStatus      string `protobuf:"bytes,7,opt,name=save_status,json=saveStatus,proto3" form:"save_status" json:"save_status,omitempty" query:"save_status"`                          // 保存状态
}

func (x *UpdateSaveRequest) Reset() {
	*x = UpdateSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSaveRequest) ProtoMessage() {}

func (x *UpdateSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSaveRequest.ProtoReflect.Descriptor instead.
func (*UpdateSaveRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSaveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateSaveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateSaveRequest) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

func (x *UpdateSaveRequest) GetSaveName() string {
	if x != nil {
		return x.SaveName
	}
	return ""
}

func (x *UpdateSaveRequest) GetSaveDescription() string {
	if x != nil {
		return x.SaveDescription
	}
	return ""
}

func (x *UpdateSaveRequest) GetSaveData() string {
	if x != nil {
		return x.SaveData
	}
	return ""
}

func (x *UpdateSaveRequest) GetSaveStatus() string {
	if x != nil {
		return x.SaveStatus
	}
	return ""
}

// 更新保存响应
type UpdateSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`            // 状态码：0-成功，非0-失败
	Message string `protobuf:"bytes,2,opt,name=message,proto3" form:"message" json:"message,omitempty" query:"message"` // 响应消息
}

func (x *UpdateSaveResponse) Reset() {
	*x = UpdateSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSaveResponse) ProtoMessage() {}

func (x *UpdateSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSaveResponse.ProtoReflect.Descriptor instead.
func (*UpdateSaveResponse) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除保存请求
type DeleteSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" form:"user_id" json:"user_id,omitempty" query:"user_id"` // 用户ID
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" form:"token" json:"token,omitempty" query:"token"`                      // 用户认证令牌
	SaveId string `protobuf:"bytes,3,opt,name=save_id,json=saveId,proto3" form:"save_id" json:"save_id,omitempty" query:"save_id"`  // 保存项ID
}

func (x *DeleteSaveRequest) Reset() {
	*x = DeleteSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSaveRequest) ProtoMessage() {}

func (x *DeleteSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSaveRequest.ProtoReflect.Descriptor instead.
func (*DeleteSaveRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSaveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteSaveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteSaveRequest) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

// 删除保存响应
type DeleteSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`            // 状态码：0-成功，非0-失败
	Message string `protobuf:"bytes,2,opt,name=message,proto3" form:"message" json:"message,omitempty" query:"message"` // 响应消息
}

func (x *DeleteSaveResponse) Reset() {
	*x = DeleteSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSaveResponse) ProtoMessage() {}

func (x *DeleteSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSaveResponse.ProtoReflect.Descriptor instead.
func (*DeleteSaveResponse) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 列出用户保存请求
type ListSavesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" form:"user_id" json:"user_id,omitempty" query:"user_id"`           // 用户ID
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" form:"token" json:"token,omitempty" query:"token"`                                // 用户认证令牌
	SaveType string `protobuf:"bytes,3,opt,name=save_type,json=saveType,proto3" form:"save_type" json:"save_type,omitempty" query:"save_type"`  // 保存类型（可选）
	Page     int32  `protobuf:"varint,4,opt,name=page,proto3" form:"page" json:"page,omitempty" query:"page"`                                   // 页码，从1开始
	PageSize int32  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" form:"page_size" json:"page_size,omitempty" query:"page_size"` // 每页数量
}

func (x *ListSavesRequest) Reset() {
	*x = ListSavesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSavesRequest) ProtoMessage() {}

func (x *ListSavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSavesRequest.ProtoReflect.Descriptor instead.
func (*ListSavesRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{9}
}

func (x *ListSavesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListSavesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListSavesRequest) GetSaveType() string {
	if x != nil {
		return x.SaveType
	}
	return ""
}

func (x *ListSavesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSavesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 列出用户保存响应
type ListSavesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32   `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`            // 状态码：0-成功，非0-失败
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" form:"message" json:"message,omitempty" query:"message"` // 响应消息
	Saves   []*Save `protobuf:"bytes,3,rep,name=saves,proto3" form:"saves" json:"saves,omitempty" query:"saves"`         // 保存项列表
	Total   int32   `protobuf:"varint,4,opt,name=total,proto3" form:"total" json:"total,omitempty" query:"total"`        // 总数量
}

func (x *ListSavesResponse) Reset() {
	*x = ListSavesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_save_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSavesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSavesResponse) ProtoMessage() {}

func (x *ListSavesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSavesResponse.ProtoReflect.Descriptor instead.
func (*ListSavesResponse) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{10}
}

func (x *ListSavesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListSavesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListSavesResponse) GetSaves() []*Save {
	if x != nil {
		return x.Saves
	}
	return nil
}

func (x *ListSavesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_save_proto protoreflect.FileDescriptor

var file_save_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x61,
	0x76, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa9, 0x02, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61,
	0x76, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x61, 0x76, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x61, 0x76, 0x65, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x73, 0x61, 0x76, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x61, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc4, 0x01, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x61, 0x76, 0x65, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x5b, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x22,
	0x58, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x73, 0x61,
	0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x04, 0x73, 0x61, 0x76, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x61, 0x76, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x22,
	0x42, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x61, 0x76, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x76, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x79, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x61, 0x76,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x61, 0x76, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x05, 0x73, 0x61, 0x76, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x32, 0xd0, 0x02, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x17,
	0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x12, 0x14,
	0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x61,
	0x76, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x17,
	0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x61, 0x76, 0x65, 0x73,
	0x12, 0x16, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x61, 0x76, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x61, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x61, 0x69, 0x2f, 0x62,
	0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x2f, 0x73, 0x61,
	0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_save_proto_rawDescOnce sync.Once
	file_save_proto_rawDescData = file_save_proto_rawDesc
)

func file_save_proto_rawDescGZIP() []byte {
	file_save_proto_rawDescOnce.Do(func() {
		file_save_proto_rawDescData = protoimpl.X.CompressGZIP(file_save_proto_rawDescData)
	})
	return file_save_proto_rawDescData
}

var file_save_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_save_proto_goTypes = []interface{}{
	(*Save)(nil),               // 0: save.Save
	(*CreateSaveRequest)(nil),  // 1: save.CreateSaveRequest
	(*CreateSaveResponse)(nil), // 2: save.CreateSaveResponse
	(*GetSaveRequest)(nil),     // 3: save.GetSaveRequest
	(*GetSaveResponse)(nil),    // 4: save.GetSaveResponse
	(*UpdateSaveRequest)(nil),  // 5: save.UpdateSaveRequest
	(*UpdateSaveResponse)(nil), // 6: save.UpdateSaveResponse
	(*DeleteSaveRequest)(nil),  // 7: save.DeleteSaveRequest
	(*DeleteSaveResponse)(nil), // 8: save.DeleteSaveResponse
	(*ListSavesRequest)(nil),   // 9: save.ListSavesRequest
	(*ListSavesResponse)(nil),  // 10: save.ListSavesResponse
}
var file_save_proto_depIdxs = []int32{
	0,  // 0: save.GetSaveResponse.save:type_name -> save.Save
	0,  // 1: save.ListSavesResponse.saves:type_name -> save.Save
	1,  // 2: save.SaveService.CreateSave:input_type -> save.CreateSaveRequest
	3,  // 3: save.SaveService.GetSave:input_type -> save.GetSaveRequest
	5,  // 4: save.SaveService.UpdateSave:input_type -> save.UpdateSaveRequest
	7,  // 5: save.SaveService.DeleteSave:input_type -> save.DeleteSaveRequest
	9,  // 6: save.SaveService.ListSaves:input_type -> save.ListSavesRequest
	2,  // 7: save.SaveService.CreateSave:output_type -> save.CreateSaveResponse
	4,  // 8: save.SaveService.GetSave:output_type -> save.GetSaveResponse
	6,  // 9: save.SaveService.UpdateSave:output_type -> save.UpdateSaveResponse
	8,  // 10: save.SaveService.DeleteSave:output_type -> save.DeleteSaveResponse
	10, // 11: save.SaveService.ListSaves:output_type -> save.ListSavesResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_save_proto_init() }
func file_save_proto_init() {
	if File_save_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_save_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Save); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSavesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_save_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSavesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_save_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_save_proto_goTypes,
		DependencyIndexes: file_save_proto_depIdxs,
		MessageInfos:      file_save_proto_msgTypes,
	}.Build()
	File_save_proto = out.File
	file_save_proto_rawDesc = nil
	file_save_proto_goTypes = nil
	file_save_proto_depIdxs = nil
}
