// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	
	"novelai/biz/router/user"
	"novelai/biz/router/save"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	user.RegisterRoutes(r)
	save.RegisterRoutes(r)
	//INSERT_POINT: DO NOT DELETE THIS LINE!
}
