// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	background "novelai/biz/router/background"
	"novelai/biz/router/save"
	"novelai/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	user.RegisterRoutes(r)
	save.RegisterRoutes(r)
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	background.Register(r)

}
